### ISSUE TITLE
Reproduction tasks

### ISSUE THREAD

**Issue by andrewschreiber** [andrewschreiber/hs-math-nlp#3]
# Goal
Publish a reproduction of [Analysing Mathematical Reasoning Abilities of Neural Models](https://arxiv.org/abs/1904.01557) in [ReScience](http://rescience.github.io/).

# Tasks
## Infra
- [x] Home Deep Learning rig config
- [x] Tensorboard
- [x] Linting & formatting
- [x] VSCode Debugger
- [x] CPU/GPU option
- [x] Deterministic/non-deterministic option
- [x] Model checkpointing
- [x] Dataloader
- [x] 8 GPU Cloud setup
- [ ] Documented code

## Models
- [x] Transformer
- [x] Simple LSTM
- [ ] Attentional LSTM

## Training / Benchmarks
- [x] Transformer
- [ ] Simple LSTM
- [ ] Attentional LSTM

## Comms
- [x] Draft
- [ ] Figures
- [ ] Submission to ReScience
- [ ] Blog post
